// en.js
module.exports = { 
    logo:"unName",
    login:"login",
    register:"register",
    loginName:"loginName",
    password:"password",
    username:"Your nickname",
    settingpwd:"setting your password",
    verificationcode:"code",
    agreement:"Clicking 'register' means that you agree and are willing to abide by the user agreement and privacy policy of this site.",
    write:"Write article",
    found:" Found",
    focus:" Focus",
    message:" Message",
    search:"Search",
    tit:"Article title",
    label:"Article label",
    type:"Article type",
    release:"Release form",

    introduction:"The article brief introduction",
    content:"article content",
    save:" save",
    setname:"Set something up!",
    newtag:"New Tag",
    public:"public",
    private:"private",
    original:"original",
    reprinted:"reprinted",
    bgm:"choose a bgm",
}