// zh.js
module.exports = { 
      logo:"未命名",
      login:"登录",
      register:"注册",
      loginName:"账号",
      password:"密码",
      username:"你的昵称",
      settingpwd:"设置密码",
      verificationcode:"验证码",
      agreement:"点击 “注册” 即表示您同意并愿意遵守本站用户协议 和 隐私政策 。",
      write:"写文章",
      found:" 发现",
      focus:" 关注",
      message:" 消息",
      music:"音乐",
      search:"搜索",
      tit:"文章标题",
      label:"文章标签",
      type:"文章类型",
      release:"发布形式",
      codeStyle:"代码块样式",

      introduction:" 文章简介",
      content:" 正文",
      save:" 保存",
      setname:"起个名字吧！",
      newtag:"新标签",
      public:"公开",
      private:"私密",
      original:"原创",
      reprinted:"转载",
      bgm:"选择一首背景音乐",
}
   